all:
  children:
    nfs:
      hosts:
        172.31.38.185:
          ansible_user: ec2-user
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@18.216.144.182"

    webservers:
      hosts:
        172.31.41.34:
          ansible_user: ec2-user
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@18.216.144.182"
        172.31.40.145:
          ansible_user: ec2-user
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@18.216.144.182"

    db:
      hosts:
        172.31.33.162:
          ansible_user: ec2-user
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@18.216.144.182"

    lb:
      hosts:
        172.31.34.139:
          ansible_user: ubuntu
          ansible_ssh_common_args: "-o ProxyJump=ubuntu@18.216.144.182"
# nfs:
#   hosts:
#     172.31.38.185:
#       ansible_user: ec2-user

# webservers:
#   hosts:
#     172.31.41.34:
#       ansible_user: ec2-user
#     172.31.40.145:
#       ansible_user: ec2-user

# db:
#   hosts:
#     172.31.33.162:
#       ansible_user: ec2-user

# lb:
#   hosts:
#     172.31.34.139:
#       ansible_user: ubuntu
# [nfs]
# 172.31.38.185 ansible_ssh_user='ec2-user'

# [webservers]
# 172.31.41.34 ansible_ssh_user='ec2-user'
# 172.31.40.145 ansible_ssh_user='ec2-user'

# [db]
# 172.31.33.162 ansible_ssh_user='ec2-user'

# [lb]
# 172.31.34.139 ansible_ssh_user='ubuntu'
