# ---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml # Replace this according to file in the static-assignments directory

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

# ---
# - hosts: all
# - name: Include dynamic variables
#   tasks:
#   import_playbook: ../static-assignments/common.yml
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - hosts: webservers
# - name: Webserver assignment
#   import_playbook: ../static-assignments/webservers.yml

---
# - hosts: all
#   name: Include dynamic variables
#   tasks:
#     - import_playbook: ../static-assignments/common.yml
#     - include: ../dynamic-assignments/env-vars.yml
#     # - import_playbook: ../static-assignments/common.yml
#     # - include_vars: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

- name: Import common file
  # import_playbook: ../static-assignments/common.yml
  tasks:
    - import_playbook: ../static-assignments/common.yml
  tags:
    - always

- name: Include dynamic env-vars variables file
  # import_playbook: ../dynamic-assignments/env-vars.yml
  tasks:
    - include_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Webserver assignment
  hosts: webservers
  tasks:
    - import_playbook: ../static-assignments/uat-webservers.yml

- name: Import database file
  hosts: db
  tasks:
    - import_playbook: ../static-assignments/db.yml

- name: Import Loadbalancers assignment
  hosts: lb
    - import_playbook: ../static-assignments/loadbalancers.yml
    when: load_balancer_is_required