---
- hosts: all
- import_playbook: ../static-assignments/common-del.yml # Replace this according to file in the static-assignments directory

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml
